export const MODERATION_ACTIONS = {
  approve: 'approve',
  reject: 'reject',
  requestEdit: 'requestEdit',
  flag: 'flag',
  ban: 'ban',
  unBan: 'unBan',
  hide: 'hide',
  unHide: 'unHide',
  notice: 'notice',
  warning: 'warning',
  systemBan: 'systemBan',
  systemFlag: 'systemFlag',
  systemNotice: 'systemNotice',
  userNotice: 'userNotice',
  userReport: 'userReport',
  userAppeal: 'userAppeal',
};